# -*- coding: utf-8 -*-
"""Process2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fwf2s8q7fo0-bzC-Y6nbbDs_QEC4DVes

**Process 2: Uploading GPS tracks to TollGuru API**
"""

import requests

def upload_gps_tracks(api_key, vehicle, csv_file_path):
    # API endpoint URL
    api_url = "https://api.tollguru.com/v1/gps-tracks-csv-upload"

    # Set up headers with API key
    headers = {
        "Content-Type": "application/octet-stream",
        "x-api-key": api_key,
    }

    # Read the binary content of the CSV file
    with open(csv_file_path, "rb") as file:
        csv_content = file.read()

    # Set up payload with vehicle information and CSV content
    payload = {
        "vehicle": vehicle,
    }

    # Make a POST request to the API
    response = requests.post(api_url, headers=headers, params=payload, data=csv_content)

    # Check if the request was successful (status code 200)
    if response.status_code == 200:
        # Parse and print the JSON response
        json_response = response.json()
        print("Toll information:", json_response)
    else:
        print(f"Error: {response.status_code} - {response.text}")

api_key = "osrm"  # Replace with your TollGuru API key
vehicle = "5AxlesTruck"  # Replace with your vehicle type
csv_file_path = "/content/raw_data.parquet"  # Replace with the path to your binary CSV file

upload_gps_tracks(api_key, vehicle, csv_file_path)

api_key = "osrm"  # Replace with your TollGuru API key
vehicle = "5AxlesTruck"  # Replace with your vehicle type
csv_file_path = "/2000_0.json"

api_key = "osrm"  # Replace with your TollGuru API key
vehicle = "5AxlesTruck"  # Replace with your vehicle type
csv_file_path = "/2000_1.json"